### ISSUE TITLE
Incompatibility with Memory Leak Fix

### ISSUE THREAD

**Issue by hound22** [Kikugie/elytra-trims#24] opened 2023-08-26 08:30 UTC
### Bug description

The game was crashing during startup and I approached quilt support, who pointed out that this was because elytra trims might be incompatible with 0.5.0+ and they were right, removing this mitigated the crashing.

### Steps to reproduce

1. Have sodium 0.5.0+ (I used sodium 0.5.2) and elytra trims version 1.3.0 mods with quilt loader version 0.20.0 and qfapi version 7.1.2+0.87.0.
2. Start minecraft. 

This will fail to start and crashes without showing why it caused an error from quilt loader. 

### Relevant logs

The log file didn't generate it seems, but here is the relevant crash report that the quilt support team narrowed down the issue to elytra trims with: 
[new crash.txt](https://github.com/kikugie/elytra-trims/files/12444873/new.crash.txt)

### Minecraft version

1.20.1

### Elytra Trims version

1.3.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment] 2023-08-26 08:36
This error is unrelated to Elytra Trims, its caused by Memory Leak Fix mod

**Comment by kikugie** [comment] 2023-08-26 08:38
Quilt has some problems with Mixin Extras, which sometimes appear, sometimes not. So it might be the case

**Comment by hound22** [comment] 2023-08-26 08:42
Oh! I'm sorry for opening this issue in that case. 
It is weird that I was able to successfully load in after removing elytra trims as well then, could this be a mod disparity/conflict perhaps?

**Comment by endigma** [comment] 2023-08-27 14:57
Confirming this only occurs when both Elytra Trims and Memory leak fix are enabled. This is on fabric. Disabling memory leak fix to "fix" the problem results in:
![image](https://github.com/kikugie/elytra-trims/assets/34945114/f8eff0e8-4bcc-40b7-8c91-c181c52fa2a8)

**Comment by kikugie** [comment] 2023-08-27 15:18
https://github.com/fxmorin/MemoryLeakFix/pull/138 this is Memory Leak Fix issue, which is already pushed and should be up in the next update

**Comment by Verdigris7** [comment] 2023-08-27 16:45
I am having the same issue and am pretty sure that this is NOT a memory leak issue, it's definitely this mod that causes the problem. It has something to do with sodium and/or memory leak fix conflicting with elytra trims. 

Memory leak fix + sodium + elytra trims will fail to load and create a fabric/quilt loader error. (Hound22's crash report is just like the one I received.) 
[Fabric_Loader_Crash.txt](https://github.com/kikugie/elytra-trims/files/12448429/Fabric_Loader_Crash.txt)


REMOVING memory leak fix while keeping sodium and elytra trims 1.3.1 will freeze the game after it loads and show those white boxes everywhere, see endigma's image.

No other crash reports generated for me.

Using any version of elytra trims from before 1.3 fixes the issue for me.

**Comment by endigma** [comment] 2023-08-29 17:30
Removing memory leak fix just blends the text, I don't understand why you're ignoring this?

**Comment by kikugie** [comment] 2023-08-29 17:34
Your issue is caused by an incompatibility with some other mod, please don't bring it into a discussion about Memory Leak Fix, that has been resolved. Although, that kind of error is probably fixed in https://github.com/kikugie/elytra-trims/actions/runs/6000651138 . If it remains with that patch, create a separate report for it.

**Closed as completed** 2023-10-01 15:12 UTC
Labels: bug, good first issue
