### ISSUE TITLE
Recipes not available on Paper servers

### ISSUE THREAD

**Issue by lum1feath3r** [Kikugie/elytra-trims#2] opened 2023-06-12 22:30 UTC
when in a server, elytra cannot be crafted with dye or glow ink to be dyed. is there a way to circumvent this for the time being using commands?

**Comment by lum1feath3r** [comment] 2023-06-12 22:32
I also can't figure out how to use banners...

**Comment by kikugie** [comment] 2023-06-12 22:40
For survival recipes to work this mod needs to be installed on the server.  
If you have access to creative mode you can customize an elytra in singleplayer, save it to a hotbar and load on the server.

**Comment by lum1feath3r** [comment] 2023-06-13 01:32
I have it on the server as well as the data pack, however putting the elytra in a crafting table with dye or glow ink does not yield a dyed elytra in my case, it does work in singleplayer as well

**Comment by kikugie** [comment] 2023-06-13 04:55
For dyes, patterns and glow it needs to have the mod on the server. Datapack works only for trims.

**Comment by lum1feath3r** [comment] 2023-06-13 09:00
I do have the mod on the server and it still doesn't work for me

**Comment by kikugie** [comment] 2023-06-13 09:14
I can confirm that it is supported on servers
![image](https://github.com/kikugie/elytra-trims/assets/50152507/a25e63c5-2322-4979-8ace-1f09909ffd36)

Please check that you have the latest version of the mod (1.1.4) and that its loaded, as shown in the server logs. The server ofc should be running fabric as well.

**Comment by kikugie** [comment] 2023-06-13 18:01
The banner & glow issues are on mod's side and will be solved in the next version.

**Comment by lum1feath3r** [comment] 2023-06-13 20:52
Awesome, thanks for the update!

**Comment by lum1feath3r** [comment] 2023-06-13 23:12
Hi so I just tried the suggested workaround in creative mode on my server and it doesn't really seem to work very well... I was able to get a plain trimmed elytra to stay trimmed long enough to equip it, but when I took it off it went back to being a vanilla elytra. I've included videos of it happening here

https://github.com/kikugie/elytra-trims/assets/38738459/496132b2-b0db-4ff8-9fba-45bad990d0aa



https://github.com/kikugie/elytra-trims/assets/38738459/837ada92-a636-4919-87a8-eba0458082d1

**Comment by kikugie** [comment] 2023-06-14 04:39
It looks like item nbt is affected by some other mod. Do you mind sharing server log with https://mclo.gs/, so I can look for incompatibility?

**Comment by lum1feath3r** [comment] 2023-06-14 09:55
this is the only mod we have on the server but we do have client side mode
and we do have the timber data pack and the durability ping datapack

https://mclo.gs/sh1lsvv

**Comment by lum1feath3r** [comment] 2023-06-14 09:57
hold on, those were the wrong logs I'm sorry

**Comment by lum1feath3r** [comment] 2023-06-14 09:59
https://mclo.gs/nnNTOaY

this is the correct logs from June 13. I misread the dates when browsing
files, my apologies

**Comment by kikugie** [comment] 2023-06-14 10:53
The last log is for a Paper server, which can't load any Fabric mods

**Comment by lum1feath3r** [comment] 2023-06-14 11:19
a lot of fabric things we use work with paper, but i suppose this isnt one
of them, after switching the modloader back to fabric it works again. I am
so sorry for the inconvenience and thank you for your help

**Comment by kikugie** [comment] 2023-06-14 11:25
Client-side mods work on Paper servers, but these recipes have unique
implementation, which requires mod to be loaded on the server.
Although I recommend running Fabric server, as there are alternatives for
Paper plugins, if you want to run Paper nonetheless, you can temporarily
switch to Fabric, craft elytra you want and switch back to Paper. Elytra
features still will be displayed.

**Comment by lum1feath3r** [comment] 2023-06-14 11:39
on the fabric server we are having trouble with glowing and banner elytra
now. the creative mode workaround works now, but we cannot craft elytra
with glowing ink sacs. we also can't craft elytra with banners, dyeing and
trimming works though!

**Comment by kikugie** [comment] 2023-06-14 11:42
Download 1.1.5 version from modrinth, I've pushed a fix for that yesterday.

**Closed as completed** 2023-06-14 21:30 UTC
