### ISSUE TITLE
[Bug]: Elytra trims with Extensions and Geode+ do not render

### ISSUE THREAD

**Issue by Rymka69** [Kikugie/elytra-trims#61] opened 2024-06-01 10:33 UTC
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.1.8 (Extensions 2.1.0)

### Affected mods

- [ ] Elytra Trims
- [X] Extensions

### Bug description

Elytra Trims extensions and Geode+ don't work that well together. What I figured out, Is that If you use non-Geode+ provided trim patern and a Geode+ trim material, the result does not render.
When applied the Item and Elytra in 3rd person renders without a trim, even though it is in the description of the item.
![image](https://github.com/kikugie/elytra-trims/assets/91845700/8d1d7c02-0bb8-449c-b2cd-f8d883004267)

In the screenshot, the trim patters (in inventory space, not hotbar) combined with any of the three materials of Geode+ in the hotbar give this preview. Only using Geode+ patterns works with Geode+ materials (Geode+ patterns also work with vanilla materials). 

Mods used while testing this:
Fabric Loader 0.15.11
Fabric API 0.92.2
Elytra Trims 3.1.8
Elytra Trims Extensions 2.1.0
Geode+ 1.2.4
MoreArmorTrims 1.2.0
Fabric Language Kotlin 1.11.0

### Steps to reproduce

1. Install Elytra Trims, Elytra Trims Extensions and Geode+ (and dependencies) 
2. Get Smithing table, Pink Topaz, Silece Smithing Template and Elytra
3. Combine them, see the result without any pattern displayed

**Comment by kikugie** [comment] 2024-06-01 20:50
Elytra Trims is configured to copy all trims specifications added by mods and resourcepacks. This issue is caused by Geode+ itself, as seen on the image. If the Geode+ author won't fix the issue, you can use [All The Trims](https://modrinth.com/mod/allthetrims) to patch the missing textures.

![image](https://github.com/kikugie/elytra-trims/assets/50152507/629dc1f3-b4fd-4abd-a570-f9c950ce4c6a)

**Closed as not planned by kikugie** 2024-06-01 20:50 UTC
Labels: bug, invalid, wontfix
