### ISSUE TITLE
[Request] Show base colour from NBT (as if dyed)?

### ISSUE THREAD

**Issue by sisby-folk** [Kikugie/elytra-trims#1] opened 2023-04-19 07:19 UTC
Not to blatantly blow your scope right after you release a really cool mod that we're definitely putting in our first 1.20 pack, but it occurs to us that dye color, like trim, is also just a random bit of NBT stapled onto an item (like `{display:{color:16007844}}` if i'm not mistaken)

Would it be possible to have the client mod make this show on the base colour of the elytra, like trimmed leather armor? 

There are other dyable elytra mods, but the ones I can find are mixed side and more invasive than the client + datapack solution which seems really cool (and i'd be unsure they'd be compatible) 

Cool mod!

**Comment by kikugie** [comment] 2023-04-19 16:32
Dying elytra turned out to be quite easy, but the problem is dyeable recipes are not datapack configurable.
![2023-04-19_18 20 29](https://user-images.githubusercontent.com/50152507/233140003-0a5539bd-a6eb-496a-9296-08364867d56a.png)  
Closest idea I have is a recipe of elytra + dyed leather chestplate, but im not sure if datapacks can be configured to copy nbt from one of the ingredients. Most of it is hardcoded into the game.

**Comment by sisby-folk** [comment] 2023-04-19 22:47
That already looks like a great addition to the client mod! (/give commands would work already) 

In terms of server side, I think making something dyable is in the realm of a server mod rather than a server datapack - mods like QDRON and Nbt-Crafting could make it datapackable, but I think that's far more complex then just mixing in to make [ElytraItem implement DyableItem](https://github.com/Fusion-Flux/Dyeable-Fishing-Lines/blob/1.18/src/main/java/net/fabricmc/example/mixin/FishingRodItemMixin.java#L25) which I *think* can run with vanilla clients, and does all the recipe stuff for you - worth a test.

**Comment by kikugie** [comment] 2023-04-29 11:20
![2023-04-29_13 19 08](https://user-images.githubusercontent.com/50152507/235299890-4fdf4c5d-d32e-4a67-a0a1-4ad892dfe5f8.png)
Updated in the last commit with better texturing

**Comment by kikugie** [comment] 2023-04-29 20:57
Released in https://modrinth.com/mod/elytra-trims/version/1.1.0+1.19.4 👍

**Closed as completed by kikugie** 2023-04-29 20:57 UTC
Labels: enhancement

**Comment by sisby-folk** [comment] 2023-04-30 03:00
Looking really good! excited to play around with it.

![javaw_g0T7SdQkpi](https://user-images.githubusercontent.com/55819817/235333410-92e05bde-2196-4c8b-a279-13c4639edc0b.png)

https://user-images.githubusercontent.com/55819817/235333462-77711b8c-5262-4585-bb12-7a0a07ae07bc.mp4
